"use client";

import { BarChart3, FileText, Lock } from "lucide-react";
import { useState } from "react";

import { Card, CardContent } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { EmptyState } from "@/components/shared/empty-state";
import { PageHeader } from "@/components/shared/page-header";
import { useMe } from "@/hooks/use-auth";
import { useNamedReport, useNamedReports } from "@/hooks/use-reports";
import { cn } from "@/lib/utils";

function humanizeColumn(col: string): string {
  return col.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

export default function ReportsPage() {
  const { data: me } = useMe();
  const canView = me?.role === "OWNER" || me?.role === "ACCOUNTANT";

  const reports = useNamedReports();
  const [selected, setSelected] = useState<string | undefined>(undefined);
  const report = useNamedReport(selected);

  if (!canView) {
    return (
      <div className="space-y-6">
        <PageHeader title="Reports" description="Run reports across your workspace." />
        <EmptyState
          icon={Lock}
          title="Owners and accountants only"
          description="Reports are limited to workspace owners and accountants."
        />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <PageHeader
        title="Reports"
        description="Run a report generated by the reporting service."
      />

      {reports.isPending ? (
        <div className="grid gap-3 sm:grid-cols-3">
          {Array.from({ length: 3 }).map((_, i) => (
            <Skeleton key={i} className="h-24" />
          ))}
        </div>
      ) : (
        <div className="grid gap-3 sm:grid-cols-3">
          {reports.data?.map((def) => (
            <button
              key={def.name}
              type="button"
              onClick={() => setSelected(def.name)}
              className={cn(
                "flex flex-col rounded-xl border bg-card p-4 text-left shadow-xs transition-all hover:-translate-y-0.5 hover:border-primary/30 hover:shadow-md",
                selected === def.name && "border-primary ring-1 ring-primary",
              )}
            >
              <div className="flex size-9 items-center justify-center rounded-lg bg-primary/10 text-primary">
                <FileText className="size-4" />
              </div>
              <p className="mt-3 font-medium">{def.title}</p>
              <p className="mt-1 text-xs text-muted-foreground">{def.description}</p>
            </button>
          ))}
        </div>
      )}

      {selected && (
        <Card>
          <CardContent>
            {report.isPending ? (
              <div className="space-y-2 py-2">
                {Array.from({ length: 5 }).map((_, i) => (
                  <Skeleton key={i} className="h-8 w-full" />
                ))}
              </div>
            ) : report.data && report.data.rows.length > 0 ? (
              <>
                <div className="mb-4">
                  <h2 className="font-heading font-semibold">{report.data.title}</h2>
                  <p className="text-sm text-muted-foreground">{report.data.description}</p>
                </div>
                <div className="overflow-x-auto">
                  <Table>
                    <TableHeader>
                      <TableRow>
                        {report.data.columns.map((col) => (
                          <TableHead key={col}>{humanizeColumn(col)}</TableHead>
                        ))}
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {report.data.rows.map((row, i) => (
                        <TableRow key={i}>
                          {report.data!.columns.map((col) => (
                            <TableCell key={col}>{String(row[col] ?? "—")}</TableCell>
                          ))}
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                </div>
              </>
            ) : (
              <EmptyState
                icon={BarChart3}
                title="No data"
                description="This report has no rows for your workspace yet."
              />
            )}
          </CardContent>
        </Card>
      )}
    </div>
  );
}
